version: "3"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es76
#    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - ./data:/usr/share/elasticsearch/data
      - ./plugins:/usr/share/elasticsearch/plugins
    environment:
      - discovery.type=single-node