spring:
  datasource:
    url:  jdbc:mysql://${mysql.url}:3306/test?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8