spring:
  application:
    name: zookeeper-client
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
server:
  port: 8345
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN