spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: root
    password: root
    hikari:
      jdbc-url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
      username: root
      password: root
      driver-class-name: oracle.jdbc.OracleDriver
      pool-name: hikari-pool
      maximum-pool-size: 20
      connection-timeout: 10000
      idle-timeout: 10000
      max-lifetime: 10000
      validation-timeout: 3000
      auto-commit: true
      connection-test-query: select 1 from dual