spring:
  application:
    name: discovery-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
