spring:
  application:
    name: boot-admin-client
  boot:
    admin:
      client:
        url: http://localhost:8421
        username: admin
        password: admin
server:
  port: 8422
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
