spring:
  application:
    name: boot-admin-server
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      client:
        url: http://localhost:${server.port}
        username: admin
        password: admin
        instance:
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
server:
  port: 8421
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
