server:
  port: 8990
spring:
  application:
    name: kafka-producer
  kafka:
    producer:
      acks: all
      retries: 3
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    streams:
      replication-factor: 3

