spring:
  application:
    name: dubbo-provider

server:
  port: 8101

dubbo:
  scan:
    base-packages: com.example.dubboprovider.service
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: nacos://${nacos.host}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}

nacos:
  host: 127.0.0.1
  port: 8848
  username: nacos
  password: nacos

